### ISSUE TITLE
Improper update

### ISSUE THREAD

**Issue by yanickrochon** [jorbuedo/react-reactive-var#1]
Performing an update to the variable produce an invalid update. The code 

```js
const reactiveVar = (newValue?: T | ((value: T) => T)) => {
    if (newValue !== undefined) {
      let nextValue = value

      if (newValue instanceof Function) {
        nextValue = newValue(value)
      } else {
        nextValue = newValue
      }

      if (equalsFunc ? !equalsFunc(nextValue, value) : nextValue !== value) {
        subscribers.forEach((handler) => handler(nextValue))
      }
      value = nextValue
    }
    return value
  }
```
result in notifying the subscribers and calling the reactive variable (getter) **before** the `value` gets updated.

Changing the code to 

```js
const reactiveVar = (newValue?: T | ((value: T) => T)) => {
    if (newValue !== undefined) {
      let nextValue = value
      let valueChanged;

      if (newValue instanceof Function) {
        nextValue = newValue(value)
      } else {
        nextValue = newValue
      }

      // set change status before updating the value
      valueChanged = equalsFunc ? !equalsFunc(nextValue, value) : nextValue !== value;

      value = nextValue      // <--- update value here, before notifying the subscribers

      if (valueChanged) {
        subscribers.forEach((handler) => handler(value))
      }
    }
    return value
  }
```
will fix this issue by updating the value **before** the subscribers reads from it.

**Comment by jorbuedo** [comment]
Nice catch! Merged.

**Comment by yanickrochon** [comment]
Hi @jorbuedo , I couldn't contact you any other way.

FYI : I have played over various features since last week, and also needed a more complex implementation with reactive dictionaries (objects), so I did create these two repositories :

* [`@yanfoo/react-dict`](https://www.npmjs.com/package/react-reactive-dict)
* [`@yanfoo/react-var`](https://www.npmjs.com/package/react-reactive-var)
